import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useCountCancelled } from '../lib/fauna'

export default function Home() {
  const numCancelled = useCountCancelled()

  return (
    <div className={styles.container}>
      <Head>
        <title>X-it</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {numCancelled ? (
          <h1>{numCancelled} meetings avoided!</h1>
        ) : (
          <h1>...thinking...</h1>
        )}
      </div>
    </div>
  )
}
