import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { listCalEvents } from '../lib/fauna'
import { useEffect, useState } from 'react'

export default function Home() {
  const [calEvents, setCalEvents] = useState([])
  useEffect(() => {
    listCalEvents()
      .then((evts) => setCalEvents(evts))
      .catch((err) => console.error('Oh no!', err.message))
  })
  return (
    <div className={styles.container}>
      <Head>
        <title>X-it</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Hello</h1>
        {calEvents.map((evt) => (
          <pre key={evt.id}>{JSON.stringify(evt, null, '    ')}</pre>
        ))}
      </div>
    </div>
  )
}
