import Head from 'next/head'
import Home from '../components/Home'
import { countCancelled } from '../lib/fauna'

export async function getServerSideProps() {
	const numCancelled = await countCancelled()
	return { props: { numCancelled } }
}

export default function App({ numCancelled }) {
	return (
		<>
			<Head>
				<title>X-it</title>

				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/fav.ico' />
			</Head>
			<Home numCancelled={numCancelled} />
		</>
	)
}
